// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// InPort is an autogenerated mock type for the InPort type
type InPort struct {
	mock.Mock
}

// ResultChan provides a mock function with given fields:
func (_m *InPort) ResultChan() <-chan int {
	ret := _m.Called()

	var r0 <-chan int
	if rf, ok := ret.Get(0).(func() <-chan int); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan int)
		}
	}

	return r0
}

type mockConstructorTestingTNewInPort interface {
	mock.TestingT
	Cleanup(func())
}

// NewInPort creates a new instance of InPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewInPort(t mockConstructorTestingTNewInPort) *InPort {
	mock := &InPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
