// Code generated by mockery v2.20.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// OutPort is an autogenerated mock type for the OutPort type
type OutPort struct {
	mock.Mock
}

// Send provides a mock function with given fields: number, transactionID
func (_m *OutPort) Send(number int, transactionID int) {
	_m.Called(number, transactionID)
}

// startListen provides a mock function with given fields:
func (_m *OutPort) startListen() {
	_m.Called()
}

type mockConstructorTestingTNewOutPort interface {
	mock.TestingT
	Cleanup(func())
}

// NewOutPort creates a new instance of OutPort. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewOutPort(t mockConstructorTestingTNewOutPort) *OutPort {
	mock := &OutPort{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
